
call Version_SetVar

set VERSION_LEFT=2.0.
set VERSION_RIGHT=%VERSION:2.0.=%

set /A VERSION_RIGHT = %VERSION_RIGHT% + 1

set VERSION=%VERSION_LEFT%%VERSION_RIGHT%
set VERSION=%VERSION: =%

echo %VERSION%> %ROOT%/%VERSION_FILENAME%

