@echo off

set PROJECT_NAME=AHR

cd..
SET PRJ_ROOT_DIR=%CD%


set PRJ_BUILD_DIR=%PRJ_ROOT_DIR%\Make
set PRJ_SOURCE_DIR=%PRJ_ROOT_DIR%\src
set PRJ_DATA_DIR=%PRJ_ROOT_DIR%\data
set PRJ_DATA_GFX_DIR=%PRJ_DATA_DIR%\gfx
set PRJ_DATA_BGM_DIR=%PRJ_DATA_DIR%\bgm
set PRJ_DATA_SFX_DIR=%PRJ_DATA_DIR%\sfx
set PRJ_TOOL_DIR=%PRJ_ROOT_DIR%\tools
set PRJ_AURORA_DIR=%PRJ_TOOL_DIR%\AuroraGT
set PRJ_SPEC_DIR=%PRJ_BUILD_DIR%\build_specification
set PRJ_BUILD_OUTPUT_DIR=%PRJ_BUILD_DIR%\build_output
set TOOLDIR=%PRJ_ROOT_DIR%\Tools

set AURORA=%PRJ_AURORA_DIR%\AuroraGT

set	USE_LZMA=0
set VC_DEBUG_DIR=%PRJ_ROOT_DIR%\Engine\Win32
set WIN32_EXE_RELEASE_DIR=%PRJ_ROOT_DIR%\build\win32
set IPHONE_PRJ_DIR=%PRJ_ROOT_DIR%\prj_iphone\

cd %PRJ_BUILD_DIR%
