#ifndef DEMO_GARAGE_MENU_DEFINES__INCLUDED__
#define DEMO_GARAGE_MENU_DEFINES__INCLUDED__

// --- for screen coordinates and other internal stuff

#include "config.h"


#if defined (R240x320)

	#define SCREENTITLE_X	(IS_PORTRAIT ? ((m_dispX + 48) >> 1) : (m_dispX >> 1))
	#define SCREENTITLE_Y	(IS_PORTRAIT ? 10 : 8)
#if defined USE_CHINESE_UNICODE_FONT
	#define SCREENTITLE_CHINESE_Y	(IS_PORTRAIT ? 10 : 1)
#endif

	#define GLOBE_START_Y 45
	#define TV_OFF_Y 0
	#define GLOBE_EXTRAHEIGHT 32

	#define LADY_PORTRAIT_X 0
	#define LADY_PORTRAIT_Y 125

	#define LADY_LANDSCAPE_X 0
	#define LADY_LANDSCAPE_X_RIGHT 230
	#define LADY_LANDSCAPE_Y 60

	#define COLORSELECTOR_ITEM_SIZE 11
	#define COLORSELECTOR_ITEM_SPACING 15

	#define COLORSELECTOR_POSITION_PORTRAIT_X (m_dispX - 20)
	#define COLORSELECTOR_POSITION_PORTRAIT_Y 180

	#define COLORSELECTOR_POSITION_LANDSCAPE_X (m_dispX - 20)
	#define COLORSELECTOR_POSITION_LANDSCAPE_Y 125

	#define USE_MAKE_CITY_ON_TWO_ROWS 1

	#define SCREENSTRIPES_PORTRAIT_WIDTH 205
	#define SCREENSTRIPES_LANDSCAPE_WIDTH 240

	#define CHOOSEDESTINATION_INFOBOX_HEIGHT_PORTRAIT 40
	#define CHOOSEDESTINATION_INFOBOX_HEIGHT_LANDSCAPE 38

	#define CHOOSE_DESTINATION_CITY_X			(m_dispX >> 1)
	#define CHOOSE_DESTINATION_CITY_Y			(IS_PORTRAIT ? 154 : 124) 
	#define CHOOSE_DESTINATION_CITY_H			(CHOOSE_DESTINATION_CITY_Y - 9)
	#define SELECTION_ARROW_DX					(- 18)
	#define SELECTION_ARROW_DY					(- 4)

	#define CHOOSEDESTINATION_INFOBOX_START_Y_PORTRAIT_OFFSET (-40)
	#define CHOOSEDESTINATION_INFOBOX_START_Y_LANDSCAPE 184

	#define CHOOSEDESTINATION_COUNTRY_X					70
	#define CHOOSEDESTINATION_COUNTRY_Y					(IS_PORTRAIT ? 216 : 166)  //SEFU
	#define CHOOSEDESTINATION_COUNTRY_TXT_Y				(CHOOSEDESTINATION_COUNTRY_Y + 15)
	#define CHOOSEDESTINATION_COUNTRY_FLAG_Y			(CHOOSEDESTINATION_COUNTRY_Y - 35)
	#define CHOOSEDESTINATION_COUNTRY_PREVIEW_X			(m_dispX - 130)
	#define CHOOSEDESTINATION_COUNTRY_PREVIEW_Y			(IS_PORTRAIT ? CHOOSEDESTINATION_COUNTRY_FLAG_Y : CHOOSEDESTINATION_COUNTRY_Y - 25)
	#define CHOOSEDESTINATION_COUNTRY_INFO_PORTRAIT_X	CHOOSEDESTINATION_COUNTRY_X
	#define CHOOSEDESTINATION_COUNTRY_INFO_PORTRAIT_Y	(CHOOSEDESTINATION_COUNTRY_Y + 14)

	#define CHOOSEDESTINATION_COUNTRY_INFO_LANDSCAPE_X	216	// TODO
	#define CHOOSEDESTINATION_COUNTRY_INFO_LANDSCAPE_Y	206

	#define CHOOSEDESTINATION_LOCKED_MONEY_OFFSET_Y 17

	#define CHOOSEDESTINATION_UNLOCK_INFO_PORTRAIT_Y 264
	#define CHOOSEDESTINATION_UNLOCK_INFO_LANDSCAPE_Y 188 //SEFU 204

	#define CHOOSEDESTINATION_LOCK_PORTRAIT_X 115
	#define CHOOSEDESTINATION_LOCK_PORTRAIT_Y 262

	#define CHOOSEDESTINATION_LOCK_LANDSCAPE_X 95
	#define CHOOSEDESTINATION_LOCK_LANDSCAPE_Y 204

	#define CHOOSEDESTINATION_ARROW_Y_OFFSET 0

	#define GAME_MODE_TV_FRAMES_X		4
	#define GAME_MODE_TV_FRAMES_Y		(IS_PORTRAIT ? 40 : 31)

	#define GAME_MODE_TV_FRAMES_X_STEP	60
	#define GAME_MODE_TRACK_NAME_Y		(IS_PORTRAIT ? 200 : 156)
	#define GAME_MODE_TRACK_NAME_X		(m_dispX >> 1) // 156 // 129
	#define GAME_MODE_NAME_X			(m_dispX >> 1)
	#define GAME_MODE_NAME_Y			(IS_PORTRAIT ? 112 : 100)
	#define GAME_MODE_NAME_H			(GAME_MODE_NAME_Y - 9)

	#define GAME_MODE_SPLINE_X			0
	#define GAME_MODE_SPLINE_Y			(IS_PORTRAIT ? -176 : -200)
	#define GAME_MODE_SPLINE_ZOOM		(IS_PORTRAIT ? -500 : -800)
	
/*SEFU
	#define CHOOSEGAMEMODE_DARKAREA_Y1_UNLOCKED_PORTRAIT 21
	#define CHOOSEGAMEMODE_DARKAREA_Y2_UNLOCKED_PORTRAIT 97
	#define CHOOSEGAMEMODE_DARKAREA_Y3_UNLOCKED_PORTRAIT 193
	#define CHOOSEGAMEMODE_DARKAREA_Y1_LOCKED_PORTRAIT 21
	#define CHOOSEGAMEMODE_DARKAREA_Y5_LOCKED_PORTRAIT 286

	#define CHOOSEGAMEMODE_DARKAREA_Y1_UNLOCKED_LANDSCAPE 21
	#define CHOOSEGAMEMODE_DARKAREA_Y2_UNLOCKED_LANDSCAPE 95
	#define CHOOSEGAMEMODE_DARKAREA_Y3_UNLOCKED_LANDSCAPE 165
	#define CHOOSEGAMEMODE_DARKAREA_Y1_LOCKED_LANDSCAPE 21
	#define CHOOSEGAMEMODE_DARKAREA_Y5_LOCKED_LANDSCAPE 222
*/
	#define UNLOCK_BAR_X		10
	#define UNLOCK_BAR_Y		(IS_PORTRAIT ? (m_dispY - 53) : (m_dispY - 48)) // (IS_PORTRAIT ? m_dispY-53 : m_dispY-44)
	#define UNLOCK_EVENT_BAR_Y	(GAME_MODE_NAME_Y + 20)
	#define	UNLOCK_BAR_CAR_Y	(IS_PORTRAIT ? (m_dispY >> 1) : (m_dispY >> 1))
	#define UNLOCK_BAR_HEIGHT	0 // (IS_PORTRAIT ? 20 : 20)
	#define	CHOOSEGAMEMODE_BEST_RIGHT_X 214

	#define TRACKSPLINE_WIDTH m_dispX
	#define TRACKSPLINETRANSLATION_X (IS_PORTRAIT ? 0 : 3700)
	#define TRACKSPLINETRANSLATION_Y (IS_PORTRAIT ? -1700 : -1100)
	#define TRACKSPLINETRANSLATION_Z (IS_PORTRAIT ? -7000 : -9000)

	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_X		(IS_PORTRAIT ? 10 : 3)
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_W		(m_dispX - CHOOSEGAMEMODE_RACE_DESCRIPTION_X * 2)
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_Y		(IS_PORTRAIT ? 133 : 118)

	#define CHOOSEGAMEMODE_CUP_OFFSET_X (-2)
	#define CHOOSEGAMEMODE_CUP_OFFSET_Y (-11)

	#define MECHANIC_GIRL_Y			(m_dispX <= m_dispY ? 126 : 83) 

	#define CHOOSEGAMELADY_INFOBOX_Y_PORTRAIT 50
	#define CHOOSEGAMELADY_INFOBOX_HEIGHT_PORTRAIT 60

	#define CHOOSEGAMELADY_INFOBOX_Y_LANDSCAPE 24
	#define CHOOSEGAMELADY_INFOBOX_HEIGHT_LANDSCAPE 35

	#define CHOOSEGAMELADY_LOCKED_EXTRAHEIGHT 12
	#define CHOOSEGAMELADY_LOCKED_TEXT_Y_OFFSET 28
	#define CHOOSEGAMELADY_LOCK_ICON_Y GIRL_DESCRIPTION_Y

	#define CHOOSEGAMELADY_ARROW_OFFSET_Y (-7)

	#define GIRL_NAME_X				(m_dispX >> 1)
	#define GIRL_NAME_Y				((m_dispX < m_dispY) ? 52 : 40)
	#define GIRL_LOCKED_Y			((m_dispX < m_dispY) ? (GIRL_NAME_Y + 30) : (GIRL_NAME_Y + 20))

	#define GIRL_DESCRIPTION_X		(m_dispX >> 1)
	#define GIRL_DESCRIPTION_Y		(IS_PORTRAIT ? GIRL_NAME_Y + 24 : GIRL_NAME_Y + 20)

	#define CHOOSEGAMELADY_GIRL_Y (IS_PORTRAIT ? 161 : 104)
	#define CHOOSEGAMELADY_GIRL1_X 0
	#define CHOOSEGAMELADY_GIRL2_X (IS_PORTRAIT ? 85 : 120)
	#define CHOOSEGAMELADY_GIRL3_X (IS_PORTRAIT ? 165 : 245)

	#define CHOOSEGAMELADY_SELECTED_GIRL_Y_OFFSET (IS_PORTRAIT ? -35 : (+8))


	#define DUEL_BET_BOX_STEP				16
	#define DUEL_BET_BOX_TITLE_H			20
	#define DUEL_BET_BOX_MARGIN_Y			6
	#define DUEL_BET_BOX_W					200
	#define DUEL_BET_BOX_H					(DUEL_BET_BOX_STEP * 3 + DUEL_BET_BOX_TITLE_H + 2 * DUEL_BET_BOX_MARGIN_Y)
	#define DUEL_BET_BOX_X					((m_dispX - DUEL_BET_BOX_W) >> 1)
	#define DUEL_BET_BOX_Y					((m_dispY - DUEL_BET_BOX_H) >> 1)
	

	#define GLOBALBOTTOMBAR_INFO_Y				m_dispY - 27
	#define GLOBALBOTTOMBAR_MONEY_X				2 //SEFU (IS_PORTRAIT ? 2 : 25)
	#define GLOBALBOTTOMBAR_COMPLETION_X		m_dispX - 1 //(IS_PORTRAIT ? m_dispX - 2 : m_dispX - 25)
#if defined USE_CHINESE_UNICODE_FONT
	#define GLOBALBOTTOMBAR_MONEY_CHINESE_X				(IS_PORTRAIT ? 2 : 35)
	#define GLOBALBOTTOMBAR_COMPLETION_CHINESE_X		(IS_PORTRAIT ? m_dispX - 2 : m_dispX - 35)
#endif
	
	#define CURRENTCARINFO_BOX_Y 21
	#define CURRENTCARINFO_BOX_HEIGHT (IS_PORTRAIT ? 85 : 65)
	#define CURRENTCARINFO_BOX_HEIGHT2 13

	#define CHOOSE_RIDE_NAME_Y			(IS_PORTRAIT ? 132 : 102)
	#define CHOOSE_RIDE_NAME_H			(CHOOSE_RIDE_NAME_Y - 9)

	#define CURRENTCARINFO_X						((m_dispX >> 1) +45)
	#define CURRENTCARINFO_TXT_X					(CURRENTCARINFO_X + 10)
	#define CURRENTCARINFO_Y						(IS_PORTRAIT ? 48 : 31)
	#define CURRENTCARINFO_SPACING					(IS_PORTRAIT ? 15 : 13)
	#define CURRENTCARINFO_LEFT_ALIGNED_TEXT_X		170
	#define CURRENTCARINFO_RIGHT_ALIGNED_TEXT_X		105

	#define CURRENTCARINFO_LOGO_X					60
	#define CURRENTCARINFO_LOGO_Y					(IS_PORTRAIT ? 70 : 60)

	#define CURRENTRECORDS_X						((m_dispX >> 1) -5)
	#define CURRENTRECORDS_TXT_X					(CURRENTRECORDS_X + 10)

	#define ACHHIEVEMENT_Y						(IS_PORTRAIT ? 48 : 38)
	#define ACHHIEVEMENT_SPACING				(IS_PORTRAIT ? 15 : 10)
	#define ACHHIEVEMENT_SPACING_PIC			(IS_PORTRAIT ? 15 : 13)
	#define ACHHIEVEMENT_SPACING_AFTER_PIC		(IS_PORTRAIT ? 10 : 8)

	#define TUNING_NAME_Y			(IS_PORTRAIT ? 102 : 102)
	#define TUNING_NAME_H			(TUNING_NAME_Y - 9)

	#define CURRENTCARTUNINGINFO_BOX_YS 21
	#define CURRENTCARTUNINGINFO_BOX_H 78

	#define CURRENTCARTUNINGINFO_ICONS_Y 120//180 //SEFU 120

	#define CURRENTCARTUNINGINFO_ARROWS_Y_OFFSET (-18)

	#define CURRENTCARTUNINGINFOLIST_Y			40//100 //SEFU 40
	#define CURRENTCARTUNINGINFOLIST_SPACING	15

	#define CURRENTCARTUNINGINFOLIST_LOGO_X		(IS_PORTRAIT ? 186 : 200)
	#define CURRENTCARTUNINGINFOLIST_LOGO_Y 67

	#define TUNING_BOX_PARTS_PER_COLUMN		3 // rax : was 4
	#define TUNING_BOX_W_MAX				140
	#define TUNING_BOX_H					65
	#define TUNING_BOX_COLORS_H				65
	#define TUNING_BOX_X_RIGHT				(m_dispX - 6)
	#define TUNING_BOX_Y					(IS_PORTRAIT ? 102 : 27)
	#define	TUNING_BOX_COLOR_FILL			RGB888TO565(0x183039)
	#define TUNING_BOX_BORDER				RGB888TO565(0xd7e0e3)
	#define TUNING_BOX_LEFT_MARGIN			16
	#define TUNING_BOX_ARROW_X				12
	#define TUNING_BOX_TOP_MARGIN			9
	#define TUNING_BOX_COLOR_Y_MARGIN		9

	#define TUNING_BOX_ARROW_WIDTH			10

	#define TUNING_BOX_NEW_OFFSET_X			110

	#define CURRENTCARTUNINGINFOLIST_ICONS_TEXT_X		4
	#define CURRENTCARTUNINGINFOLIST_ICONS_TEXT_Y		146 //200 //SEFU 142

	#define CHOOSEYOURRIDE_SCROLLBAR_STEP_X 12
	#define CHOOSEYOURRIDE_SCROLLBAR_START_X (m_dispX/2) - ((stepX*12) >> 1)

	#define MAINSTATE_MENU_X			40
	#define MAINSTATE_MENU_Y			(IS_PORTRAIT ? 50 : 39)
	#define MAINSTATE_MENU_SPACING		(IS_PORTRAIT ? 17 : 14)
#ifdef HAS_ACHIEVEMENTS
	#define GARAGE_MENU_Y			(IS_PORTRAIT ? 46 : 35)
#endif

#elif defined R352x416

	#define SCREENTITLE_Y (-1)

	#define TV_OFF_Y 20
	#define GLOBE_START_Y (45 + TV_OFF_Y)
	#define GLOBE_EXTRAHEIGHT 32

	#define LADY_PORTRAIT_X 0
	#define LADY_PORTRAIT_Y (125 + 48 - 20)

	#define LADY_LANDSCAPE_X 0
	#define LADY_LANDSCAPE_X_RIGHT 230
	#define LADY_LANDSCAPE_Y (60 + 48 - 20)

	#define COLORSELECTOR_ITEM_SIZE 11
	#define COLORSELECTOR_ITEM_SPACING 15

	#define COLORSELECTOR_POSITION_PORTRAIT_X (m_dispX - 20)
	#define COLORSELECTOR_POSITION_PORTRAIT_Y 180

	#define COLORSELECTOR_POSITION_LANDSCAPE_X (m_dispX - 20)
	#define COLORSELECTOR_POSITION_LANDSCAPE_Y 125

	#define USE_MAKE_CITY_ON_TWO_ROWS 0

	#define SCREENSTRIPES_PORTRAIT_WIDTH 205
	#define SCREENSTRIPES_LANDSCAPE_WIDTH 240

	#define CHOOSEDESTINATION_INFOBOX_HEIGHT_PORTRAIT 40
	#define CHOOSEDESTINATION_INFOBOX_HEIGHT_LANDSCAPE 38

	#define CHOOSEDESTINATION_INFOBOX_START_Y_PORTRAIT_OFFSET (-40)
	#define CHOOSEDESTINATION_INFOBOX_START_Y_LANDSCAPE 184

	#define CHOOSEDESTINATION_COUNTRY_X		70  // 90
	#define CHOOSEDESTINATION_COUNTRY_INFO_PORTRAIT_X	CHOOSEDESTINATION_COUNTRY_X
	#define CHOOSEDESTINATION_COUNTRY_INFO_PORTRAIT_Y	(CHOOSEDESTINATION_COUNTRY_Y + 14)

	#define CHOOSEDESTINATION_COUNTRY_Y				(IS_PORTRAIT ? 244 : 206)
	#define CHOOSEDESTINATION_COUNTRY_TXT_Y			(CHOOSEDESTINATION_COUNTRY_Y + 15)
	#define CHOOSEDESTINATION_COUNTRY_FLAG_Y		(CHOOSEDESTINATION_COUNTRY_Y - 35)
	#define CHOOSEDESTINATION_COUNTRY_PREVIEW_X		(m_dispX - 140)
	#define CHOOSEDESTINATION_COUNTRY_PREVIEW_Y		(CHOOSEDESTINATION_COUNTRY_Y - 30)
	#define CHOOSEDESTINATION_COUNTRY_INFO_PORTRAIT_Y 261

	#define CHOOSEDESTINATION_COUNTRY_INFO_LANDSCAPE_X	170	// TODO
	#define CHOOSEDESTINATION_COUNTRY_INFO_LANDSCAPE_Y	206

	#define CHOOSEDESTINATION_LOCKED_MONEY_OFFSET_Y 17

	#define CHOOSEDESTINATION_UNLOCK_INFO_PORTRAIT_Y 244
	#define CHOOSEDESTINATION_UNLOCK_INFO_LANDSCAPE_Y 204

	#define CHOOSEDESTINATION_LOCK_PORTRAIT_X 115
	#define CHOOSEDESTINATION_LOCK_PORTRAIT_Y 262

	#define CHOOSEDESTINATION_LOCK_LANDSCAPE_X 95
	#define CHOOSEDESTINATION_LOCK_LANDSCAPE_Y 204

	#define CHOOSEDESTINATION_ARROW_Y_OFFSET 0

	#define GAME_MODE_TV_FRAMES_X		4
	#define GAME_MODE_TV_FRAMES_Y		49

	#define GAME_MODE_TV_FRAMES_X_STEP	60
	#define GAME_MODE_TRACK_NAME_Y		27
	#define GAME_MODE_TRACK_NAME_X		129
	#define GAME_MODE_NAME_X			129

	#define CHOOSEGAMEMODE_DARKAREA_Y1_UNLOCKED_PORTRAIT 21
	#define CHOOSEGAMEMODE_DARKAREA_Y2_UNLOCKED_PORTRAIT 97
	#define CHOOSEGAMEMODE_DARKAREA_Y3_UNLOCKED_PORTRAIT 193
	#define CHOOSEGAMEMODE_DARKAREA_Y1_LOCKED_PORTRAIT 21
	#define CHOOSEGAMEMODE_DARKAREA_Y5_LOCKED_PORTRAIT 286

	#define CHOOSEGAMEMODE_DARKAREA_Y1_UNLOCKED_LANDSCAPE 21
	#define CHOOSEGAMEMODE_DARKAREA_Y2_UNLOCKED_LANDSCAPE 95
	#define CHOOSEGAMEMODE_DARKAREA_Y3_UNLOCKED_LANDSCAPE 165
	#define CHOOSEGAMEMODE_DARKAREA_Y1_LOCKED_LANDSCAPE 21
	#define CHOOSEGAMEMODE_DARKAREA_Y5_LOCKED_LANDSCAPE 222

	#define UNLOCK_BAR_Y	(IS_PORTRAIT ? m_dispY-53 : m_dispY-34)
	#define UNLOCK_EVENT_BAR_Y	(GAME_MODE_NAME_Y + 20)
	#define UNLOCK_BAR_HEIGHT	(IS_PORTRAIT ? 20 : 20)
	#define	CHOOSEGAMEMODE_BEST_RIGHT_X 214

	#define TRACKSPLINE_WIDTH m_dispX
	#define TRACKSPLINETRANSLATION_X 0
	#define TRACKSPLINETRANSLATION_Y 0
	#define TRACKSPLINETRANSLATION_Z -7000

	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_X_PORTRAIT 77
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_X_LANDSCAPE 3
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_W_LANDSCAPE 230
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_Y_OFFSET 13

	#define CHOOSEGAMEMODE_CUP_OFFSET_X (-2)
	#define CHOOSEGAMEMODE_CUP_OFFSET_Y (-11)

	#define MECHANIC_GIRL_Y			(m_dispX < m_dispY ? 126 : 83) 

	#define CHOOSEGAMELADY_INFOBOX_Y_PORTRAIT 50
	#define CHOOSEGAMELADY_INFOBOX_HEIGHT_PORTRAIT 60

	#define CHOOSEGAMELADY_INFOBOX_Y_LANDSCAPE 24
	#define CHOOSEGAMELADY_INFOBOX_HEIGHT_LANDSCAPE 35

	#define CHOOSEGAMELADY_LOCKED_EXTRAHEIGHT 12
	#define CHOOSEGAMELADY_LOCKED_TEXT_Y_OFFSET 28
	#define CHOOSEGAMELADY_LOCK_ICON_Y GIRL_DESCRIPTION_Y

	#define CHOOSEGAMELADY_ARROW_OFFSET_Y (-7)

	#define GIRL_NAME_X				(m_dispX >> 1)
	#define GIRL_NAME_Y				((m_dispX<m_dispY) ? 52 : 29)
	#define GIRL_LOCKED_Y			((m_dispX < m_dispY) ? (GIRL_NAME_Y + 30) : (GIRL_NAME_Y + 20))

	#define GIRL_DESCRIPTION_X		(m_dispX >> 1)
	#define GIRL_DESCRIPTION_Y		(GIRL_NAME_Y + 24)

	#define CHOOSEGAMELADY_GIRL_Y (IS_PORTRAIT ? 162 : 98)
	#define CHOOSEGAMELADY_GIRL1_X 0
	#define CHOOSEGAMELADY_GIRL2_X (IS_PORTRAIT ? 85 : 120)
	#define CHOOSEGAMELADY_GIRL3_X (IS_PORTRAIT ? 165 : 245)

	#define CHOOSEGAMELADY_SELECTED_GIRL_Y_OFFSET (IS_PORTRAIT ? -34 : -18)

	#define DUEL_BET_BOX_STEP				16
	#define DUEL_BET_BOX_TITLE_H			(CHighGear::GetInstance()->CurrentChineseLanguage() ? 17 : 15)
	#define DUEL_BET_BOX_MARGIN_Y			4
	#define DUEL_BET_BOX_X					110
	#define DUEL_BET_BOX_Y					(CHighGear::GetInstance()->CurrentChineseLanguage() ? 112 : 116)
	#define DUEL_BET_BOX_W					130
	//#define DUEL_BET_BOX_H					(CHighGear::GetInstance()->CurrentChineseLanguage() ? 74 : 70)
	#define DUEL_BET_BOX_H					(DUEL_BET_BOX_STEP * 3 + DUEL_BET_BOX_TITLE_H + 2 * DUEL_BET_BOX_MARGIN_Y)
	

	#define GLOBALBOTTOMBAR_INFO_Y (IS_PORTRAIT ? m_dispY - 30 : m_dispY - 13)
	#define GLOBALBOTTOMBAR_MONEY_X (IS_PORTRAIT ? 2 : 25)
	#define GLOBALBOTTOMBAR_COMPLETION_X (IS_PORTRAIT ? m_dispX - 2 : m_dispX - 25)

	#define CURRENTCARINFO_BOX_Y 21
	#define CURRENTCARINFO_BOX_HEIGHT (IS_PORTRAIT ? 85 : 65)
	#define CURRENTCARINFO_BOX_HEIGHT2 13

	#define CURRENTCARINFO_Y (IS_PORTRAIT ? 26 : 17)
	#define CURRENTCARINFO_SPACING (IS_PORTRAIT ? 15 : 13)
	#define CURRENTCARINFO_LEFT_ALIGNED_TEXT_X 170
	#define CURRENTCARINFO_RIGHT_ALIGNED_TEXT_X 105

	#define CURRENTCARINFO_LOGO_X 54
	#define CURRENTCARINFO_LOGO_Y (IS_PORTRAIT ? 70 : 60)

	#define CURRENTCARTUNINGINFO_BOX_YS 21
	#define CURRENTCARTUNINGINFO_BOX_H 78

	#define CURRENTCARTUNINGINFO_ICONS_Y 120

	#define CURRENTCARTUNINGINFO_ARROWS_Y_OFFSET (-18)

	#define CURRENTCARTUNINGINFOLIST_Y 23
	#define CURRENTCARTUNINGINFOLIST_SPACING 15

	#define CURRENTCARTUNINGINFOLIST_LOGO_X 185
	#define CURRENTCARTUNINGINFOLIST_LOGO_Y 67

	#define TUNING_BOX_PARTS_PER_COLUMN		4
	#define TUNING_BOX_W_MAX				130
	#define TUNING_BOX_H					70
	#define TUNING_BOX_COLORS_H				70
	#define TUNING_BOX_X_RIGHT				(IS_PORTRAIT ? 240 : 290)
	#define TUNING_BOX_Y					26
	#define	TUNING_BOX_COLOR_FILL			0x0000
	#define TUNING_BOX_BORDER				0x0F0F
	#define TUNING_BOX_LEFT_MARGIN			4
	#define TUNING_BOX_TOP_MARGIN			9
	#define TUNING_BOX_COLOR_Y_MARGIN		9

	#define TUNING_BOX_ARROW_WIDTH			10

	#define TUNING_BOX_NEW_OFFSET_X			110

	#define CURRENTCARTUNINGINFOLIST_ICONS_TEXT_X		4
	#define CURRENTCARTUNINGINFOLIST_ICONS_TEXT_Y		142

	#define CHOOSEYOURRIDE_SCROLLBAR_STEP_X 12
	#define CHOOSEYOURRIDE_SCROLLBAR_START_X (m_dispX/2) - ((stepX*12) >> 1)

#elif defined R176x208

	#define SCREENTITLE_X	((m_dispX + 16) >> 1)
	#define SCREENTITLE_Y 6

	#define GLOBE_START_Y (37)
	#define TV_OFF_Y 0
	#define GLOBE_EXTRAHEIGHT 32

	#define LADY_PORTRAIT_X 0
	#define LADY_PORTRAIT_Y 67

	#define LADY_LANDSCAPE_X 0
	#define LADY_LANDSCAPE_X_RIGHT 118
	#define LADY_LANDSCAPE_Y 60

	#define COLORSELECTOR_ITEM_SIZE 7
	#define COLORSELECTOR_ITEM_SPACING 11

	#define COLORSELECTOR_POSITION_PORTRAIT_X (m_dispX - 20)
	#define COLORSELECTOR_POSITION_PORTRAIT_Y (180 - 56 - 20)

	#define COLORSELECTOR_POSITION_LANDSCAPE_X (m_dispX - 20)
	#define COLORSELECTOR_POSITION_LANDSCAPE_Y (125 - 56 - 20)

	#define USE_MAKE_CITY_ON_TWO_ROWS 0

	#define SCREENSTRIPES_PORTRAIT_WIDTH 148
	#define SCREENSTRIPES_LANDSCAPE_WIDTH 176

	#define CHOOSEDESTINATION_INFOBOX_HEIGHT_PORTRAIT 28
	#define CHOOSEDESTINATION_INFOBOX_HEIGHT_LANDSCAPE 38

	#define CHOOSE_DESTINATION_CITY_X			(m_dispX >> 1)
	#define CHOOSE_DESTINATION_CITY_Y			100
	#define CHOOSE_DESTINATION_CITY_H			(CHOOSE_DESTINATION_CITY_Y - 9)
	#define SELECTION_ARROW_DX					(- 12)
//geo
	#define SELECTION_ARROW_DY					(- 2)

	#define CHOOSEDESTINATION_INFOBOX_START_Y_PORTRAIT_OFFSET (-31)
	#define CHOOSEDESTINATION_INFOBOX_START_Y_LANDSCAPE 184

//geo
	#define CHOOSEDESTINATION_COUNTRY_X					66//50 
	#define CHOOSEDESTINATION_COUNTRY_Y					(IS_PORTRAIT ? 150 : 103)
	#define CHOOSEDESTINATION_COUNTRY_TXT_Y				(CHOOSEDESTINATION_COUNTRY_Y + 10)
	#define CHOOSEDESTINATION_COUNTRY_FLAG_Y			(CHOOSEDESTINATION_COUNTRY_Y - 30)
//geo
	#define CHOOSEDESTINATION_COUNTRY_PREVIEW_X			(m_dispX - 93)
	#define CHOOSEDESTINATION_COUNTRY_PREVIEW_Y			(CHOOSEDESTINATION_COUNTRY_Y - 30)
	#define CHOOSEDESTINATION_COUNTRY_INFO_PORTRAIT_X	CHOOSEDESTINATION_COUNTRY_X
	#define CHOOSEDESTINATION_COUNTRY_INFO_PORTRAIT_Y	(CHOOSEDESTINATION_COUNTRY_Y + 14)

	#define CHOOSEDESTINATION_COUNTRY_INFO_LANDSCAPE_X	180	// TODO
	#define CHOOSEDESTINATION_COUNTRY_INFO_LANDSCAPE_Y  (206 - 103)

	#define CHOOSEDESTINATION_UNLOCK_INFO_PORTRAIT_Y 144
	#define CHOOSEDESTINATION_UNLOCK_INFO_LANDSCAPE_Y (204 - 103)

	#define CHOOSEDESTINATION_LOCKED_MONEY_OFFSET_Y 11

	#define CHOOSEDESTINATION_LOCK_PORTRAIT_X 87
	#define CHOOSEDESTINATION_LOCK_PORTRAIT_Y 161

	#define CHOOSEDESTINATION_LOCK_LANDSCAPE_X 95
	#define CHOOSEDESTINATION_LOCK_LANDSCAPE_Y (204 - 103)

	#define CHOOSEDESTINATION_ARROW_Y_OFFSET (-17)

	#define GAME_MODE_TV_FRAMES_X		1
	#define GAME_MODE_TV_FRAMES_Y		24

	#define GAME_MODE_TV_FRAMES_X_STEP	44
	#define GAME_MODE_TRACK_NAME_X		(m_dispX >> 1)
	#define GAME_MODE_TRACK_NAME_Y		83
	#define GAME_MODE_NAME_X			(m_dispX >> 1)
	#define GAME_MODE_NAME_Y			70
	#define GAME_MODE_NAME_H			(GAME_MODE_NAME_Y - 9)

	#define GAME_MODE_SPLINE_X			0
	#define GAME_MODE_SPLINE_Y			(IS_PORTRAIT ? -110 : -90)
	#define GAME_MODE_SPLINE_ZOOM		(IS_PORTRAIT ? -600 : -800)
/*
	#define CHOOSEGAMEMODE_DARKAREA_Y1_UNLOCKED_PORTRAIT 14
	#define CHOOSEGAMEMODE_DARKAREA_Y2_UNLOCKED_PORTRAIT 64
	#define CHOOSEGAMEMODE_DARKAREA_Y3_UNLOCKED_PORTRAIT 139
	#define CHOOSEGAMEMODE_DARKAREA_Y1_LOCKED_PORTRAIT 14
	#define CHOOSEGAMEMODE_DARKAREA_Y5_LOCKED_PORTRAIT 139

	#define CHOOSEGAMEMODE_DARKAREA_Y1_UNLOCKED_LANDSCAPE 14
	#define CHOOSEGAMEMODE_DARKAREA_Y2_UNLOCKED_LANDSCAPE 95
	#define CHOOSEGAMEMODE_DARKAREA_Y3_UNLOCKED_LANDSCAPE 165
	#define CHOOSEGAMEMODE_DARKAREA_Y1_LOCKED_LANDSCAPE 14
	#define CHOOSEGAMEMODE_DARKAREA_Y5_LOCKED_LANDSCAPE 222
*/
	#define UNLOCK_BAR_X	10
	#define UNLOCK_BAR_Y	(IS_PORTRAIT ? m_dispY - 38 : m_dispY - 34)
	#define UNLOCK_EVENT_BAR_Y	(GAME_MODE_NAME_Y + 20)
	#define	UNLOCK_BAR_CAR_Y	(IS_PORTRAIT ? (m_dispY >> 1) : (m_dispY >> 1))
	#define UNLOCK_BAR_HEIGHT	(IS_PORTRAIT ? 41 : 20)
	#define	CHOOSEGAMEMODE_BEST_RIGHT_X 160

	#define TRACKSPLINE_WIDTH m_dispX
	#define TRACKSPLINETRANSLATION_X 0
	#define TRACKSPLINETRANSLATION_Y -600
	#define TRACKSPLINETRANSLATION_Z -12000
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_X		(IS_PORTRAIT ? 5 : 3)
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_W		(IS_PORTRAIT ? 166 : 200)
//geo
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_Y		(IS_PORTRAIT ? 83 : 90)
/*
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_X_PORTRAIT 60
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_X_LANDSCAPE 3
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_W_LANDSCAPE 230
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_Y_OFFSET 5
*/
	#define CHOOSEGAMEMODE_CUP_OFFSET_X (14)
	#define CHOOSEGAMEMODE_CUP_OFFSET_Y (21)

	#define MECHANIC_GIRL_Y			(IS_PORTRAIT ? LADY_PORTRAIT_Y : LADY_LANDSCAPE_Y)

	#define CHOOSEGAMELADY_INFOBOX_Y_PORTRAIT 17
	#define CHOOSEGAMELADY_INFOBOX_HEIGHT_PORTRAIT 36

	#define CHOOSEGAMELADY_INFOBOX_Y_LANDSCAPE 24
	#define CHOOSEGAMELADY_INFOBOX_HEIGHT_LANDSCAPE 35

	#define CHOOSEGAMELADY_LOCKED_EXTRAHEIGHT 12
	#define CHOOSEGAMELADY_LOCKED_TEXT_Y_OFFSET 26
	#define CHOOSEGAMELADY_LOCK_ICON_Y (GIRL_DESCRIPTION_Y + 9)

	#define CHOOSEGAMELADY_ARROW_OFFSET_Y (-3)

	#define GIRL_NAME_X				(m_dispX >> 1)
	#define GIRL_NAME_Y				(IS_PORTRAIT ? 32 : 29)
	#define GIRL_LOCKED_Y			((m_dispX < m_dispY) ? (GIRL_NAME_Y + 30) : (GIRL_NAME_Y + 20))

	#define GIRL_DESCRIPTION_X		(m_dispX >> 1)
//geo
	#define GIRL_DESCRIPTION_Y		(GIRL_NAME_Y + 14)

	#define CHOOSEGAMELADY_GIRL_Y (IS_PORTRAIT ? 100 : 98)
	#define CHOOSEGAMELADY_GIRL1_X 0
	#define CHOOSEGAMELADY_GIRL2_X (IS_PORTRAIT ? 63 : 120)
//geo
	#define CHOOSEGAMELADY_GIRL3_X (IS_PORTRAIT ? 122 : 178)
//geo
	#define CHOOSEGAMELADY_SELECTED_GIRL_Y_OFFSET (IS_PORTRAIT ? -25 : -25)

	#define DUEL_BET_BOX_STEP				16
	#define DUEL_BET_BOX_TITLE_H			18
	#define DUEL_BET_BOX_MARGIN_Y			4
//geo
	#define DUEL_BET_BOX_X					30//40
	#define DUEL_BET_BOX_Y					82
	#define DUEL_BET_BOX_W					140//120
	//#define DUEL_BET_BOX_H					70
	#define DUEL_BET_BOX_H					(DUEL_BET_BOX_STEP * 3 + DUEL_BET_BOX_TITLE_H + 2 * DUEL_BET_BOX_MARGIN_Y)

//geo
	#define GLOBALBOTTOMBAR_INFO_Y (IS_PORTRAIT ? m_dispY - 20 : m_dispY - 21)
	#define GLOBALBOTTOMBAR_MONEY_X (IS_PORTRAIT ? 2 : 25)
	#define GLOBALBOTTOMBAR_COMPLETION_X (IS_PORTRAIT ? m_dispX - 2 : m_dispX - 25)

	#define CURRENTCARINFO_BOX_Y 14
	#define CURRENTCARINFO_BOX_HEIGHT (IS_PORTRAIT ? 72 : 65)
	#define CURRENTCARINFO_BOX_HEIGHT2 13

	#define CHOOSE_RIDE_NAME_Y			(IS_PORTRAIT ? 90 : 80) 
	#define CHOOSE_RIDE_NAME_H			(CHOOSE_RIDE_NAME_Y - 9)

	#define CURRENTCARINFO_X				((m_dispX >> 1) + 30)
	#define CURRENTCARINFO_TXT_X			(CURRENTCARINFO_X + 7)
//geo
	#define CURRENTCARINFO_Y				(IS_PORTRAIT ? 24 : 17)
	#define CURRENTCARINFO_SPACING (IS_PORTRAIT ? 13 : 13)
	#define CURRENTCARINFO_LEFT_ALIGNED_TEXT_X 105
	#define CURRENTCARINFO_RIGHT_ALIGNED_TEXT_X 55

	#define CURRENTCARINFO_LOGO_X 45
	#define CURRENTCARINFO_LOGO_Y (IS_PORTRAIT ? 49 : 40)
//geo
	#define CURRENTRECORDS_X						((m_dispX >> 1))
	#define CURRENTRECORDS_TXT_X					(CURRENTRECORDS_X)

	#define TUNING_NAME_Y			(IS_PORTRAIT ? 85 : 85)
	#define TUNING_NAME_H			(TUNING_NAME_Y - 9)

	#define CURRENTCARTUNINGINFO_BOX_YS 14
	#define CURRENTCARTUNINGINFO_BOX_H 72
//geo
	#define CURRENTCARTUNINGINFO_ICONS_Y 98//105
	#define CURRENTCARTUNINGINFO_ARROWS_Y_OFFSET (-14)//(-21)

	#define CURRENTCARTUNINGINFOLIST_Y 30
	#define CURRENTCARTUNINGINFOLIST_SPACING 12
//geo
	#define CURRENTCARTUNINGINFOLIST_LOGO_X 141//155
	#define CURRENTCARTUNINGINFOLIST_LOGO_Y 57

	#define TUNING_BOX_PARTS_PER_COLUMN		4
	#define TUNING_BOX_W_MAX				114
	#define TUNING_BOX_H					70
	#define TUNING_BOX_COLORS_H				70
	#define TUNING_BOX_X_RIGHT				(IS_PORTRAIT ? 166 : 214)
	#define TUNING_BOX_Y					85
	#define	TUNING_BOX_COLOR_FILL			0x0000
	#define TUNING_BOX_BORDER				0x0F0F
//geo
	#define TUNING_BOX_LEFT_MARGIN			12//4
	#define TUNING_BOX_ARROW_X				10
	#define TUNING_BOX_TOP_MARGIN			2
	#define TUNING_BOX_COLOR_Y_MARGIN		11//9

	#define TUNING_BOX_ARROW_WIDTH			10
//geo
	#define TUNING_BOX_NEW_OFFSET_X			87//80

//geo
	#define CURRENTCARTUNINGINFOLIST_ICONS_TEXT_X		4
	#define CURRENTCARTUNINGINFOLIST_ICONS_TEXT_Y		116//124

	#define CHOOSEYOURRIDE_SCROLLBAR_STEP_X 10
	#define CHOOSEYOURRIDE_SCROLLBAR_START_X (m_dispX - stepX * 11)

	#define MAINSTATE_MENU_X				30
	#define MAINSTATE_MENU_Y				30
	#define MAINSTATE_MENU_SPACING		(IS_PORTRAIT ? 12 : 12)

#elif defined R320x480

	#define SCREENTITLE_X	((m_dispX + 48) >> 1)
	#define SCREENTITLE_Y	10 // (-1)

	#define GLOBE_START_Y 45
	#define TV_OFF_Y 0
	#define GLOBE_EXTRAHEIGHT 32

	#define LADY_PORTRAIT_X 0
	#define LADY_PORTRAIT_Y 125

	#define LADY_LANDSCAPE_X 0
	#define LADY_LANDSCAPE_X_RIGHT 230
	#define LADY_LANDSCAPE_Y 60

	#define COLORSELECTOR_ITEM_SIZE 11
	#define COLORSELECTOR_ITEM_SPACING 15

	#define COLORSELECTOR_POSITION_PORTRAIT_X (m_dispX - 20)
	#define COLORSELECTOR_POSITION_PORTRAIT_Y 180

	#define COLORSELECTOR_POSITION_LANDSCAPE_X (m_dispX - 20)
	#define COLORSELECTOR_POSITION_LANDSCAPE_Y 125

	#define USE_MAKE_CITY_ON_TWO_ROWS 1

	#define SCREENSTRIPES_PORTRAIT_WIDTH 205
	#define SCREENSTRIPES_LANDSCAPE_WIDTH 240

	#define CHOOSEDESTINATION_INFOBOX_HEIGHT_PORTRAIT 40
	#define CHOOSEDESTINATION_INFOBOX_HEIGHT_LANDSCAPE 38

	#define CHOOSE_DESTINATION_CITY_X			(m_dispX >> 1)
	#define CHOOSE_DESTINATION_CITY_Y			154 //SEFU 200 // (154)
	#define CHOOSE_DESTINATION_CITY_H			(CHOOSE_DESTINATION_CITY_Y - 9)
	#define SELECTION_ARROW_DX					(- 16)
	#define SELECTION_ARROW_DY					(- 4)

	#define CHOOSEDESTINATION_INFOBOX_START_Y_PORTRAIT_OFFSET (-40)
	#define CHOOSEDESTINATION_INFOBOX_START_Y_LANDSCAPE 184

	#define CHOOSEDESTINATION_COUNTRY_X		90
	#define CHOOSEDESTINATION_COUNTRY_Y					(IS_PORTRAIT ? 216 : 174)
	#define CHOOSEDESTINATION_COUNTRY_TXT_Y				(CHOOSEDESTINATION_COUNTRY_Y + 15)
	#define CHOOSEDESTINATION_COUNTRY_FLAG_Y			(CHOOSEDESTINATION_COUNTRY_Y - 35)
	#define CHOOSEDESTINATION_COUNTRY_PREVIEW_X			(m_dispX - 140)
	#define CHOOSEDESTINATION_COUNTRY_PREVIEW_Y			(CHOOSEDESTINATION_COUNTRY_Y - 30)
	#define CHOOSEDESTINATION_COUNTRY_INFO_PORTRAIT_X	CHOOSEDESTINATION_COUNTRY_X
	#define CHOOSEDESTINATION_COUNTRY_INFO_PORTRAIT_Y	(CHOOSEDESTINATION_COUNTRY_Y + 14)

	#define CHOOSEDESTINATION_COUNTRY_INFO_LANDSCAPE_X	216	// TODO
	#define CHOOSEDESTINATION_COUNTRY_INFO_LANDSCAPE_Y	206

	#define CHOOSEDESTINATION_LOCKED_MONEY_OFFSET_Y 17

	#define CHOOSEDESTINATION_UNLOCK_INFO_PORTRAIT_Y 244
	#define CHOOSEDESTINATION_UNLOCK_INFO_LANDSCAPE_Y 188 //SEFU 204

	#define CHOOSEDESTINATION_LOCK_PORTRAIT_X 115
	#define CHOOSEDESTINATION_LOCK_PORTRAIT_Y 262

	#define CHOOSEDESTINATION_LOCK_LANDSCAPE_X 95
	#define CHOOSEDESTINATION_LOCK_LANDSCAPE_Y 204

	#define CHOOSEDESTINATION_ARROW_Y_OFFSET 0

	#define GAME_MODE_TV_FRAMES_X		4
	#define GAME_MODE_TV_FRAMES_Y		40 // 49

	#define GAME_MODE_TV_FRAMES_X_STEP	60
	#define GAME_MODE_TRACK_NAME_Y		190 // 147 // 27
	#define GAME_MODE_TRACK_NAME_X		(m_dispX >> 1) // 156 // 129
	#define GAME_MODE_NAME_X			(m_dispX >> 1)
	#define GAME_MODE_NAME_Y			112
	#define GAME_MODE_NAME_H			(GAME_MODE_NAME_Y - 9)
	
	#define GAME_MODE_SPLINE_X			0
	#define GAME_MODE_SPLINE_Y			(IS_PORTRAIT ? 193 : 165)
	#define GAME_MODE_SPLINE_ZOOM		(IS_PORTRAIT ? -600 : -800)
	
	#define UNLOCK_BAR_X	10
	#define UNLOCK_BAR_Y	(IS_PORTRAIT ? m_dispY-53 : m_dispY-44)
	#define UNLOCK_EVENT_BAR_Y	(GAME_MODE_NAME_Y + 20)
	#define	UNLOCK_BAR_CAR_Y	(IS_PORTRAIT ? (m_dispY >> 1) : (m_dispY >> 1))
	#define UNLOCK_BAR_HEIGHT	0 // (IS_PORTRAIT ? 20 : 20)
	#define	CHOOSEGAMEMODE_BEST_RIGHT_X 214


	#define UNLOCK_BAR_X	10
	#define TRACKSPLINE_WIDTH m_dispX
	#define TRACKSPLINETRANSLATION_X 0
	#define TRACKSPLINETRANSLATION_Y -1700
	#define TRACKSPLINETRANSLATION_Z -7000
	
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_X		(IS_PORTRAIT ? 10 : 3)
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_W		(IS_PORTRAIT ? 220 : 220)
	#define CHOOSEGAMEMODE_RACE_DESCRIPTION_Y		(IS_PORTRAIT ? 133 : 119)

	#define CHOOSEGAMEMODE_CUP_OFFSET_X (-2)
	#define CHOOSEGAMEMODE_CUP_OFFSET_Y (-11)

	#define MECHANIC_GIRL_Y			(m_dispX < m_dispY ? 126 : 83) 

	#define CHOOSEGAMELADY_INFOBOX_Y_PORTRAIT 50
	#define CHOOSEGAMELADY_INFOBOX_HEIGHT_PORTRAIT 60

	#define CHOOSEGAMELADY_INFOBOX_Y_LANDSCAPE 24
	#define CHOOSEGAMELADY_INFOBOX_HEIGHT_LANDSCAPE 35

	#define CHOOSEGAMELADY_LOCKED_EXTRAHEIGHT 12
	#define CHOOSEGAMELADY_LOCKED_TEXT_Y_OFFSET 28
	#define CHOOSEGAMELADY_LOCK_ICON_Y GIRL_DESCRIPTION_Y

	#define CHOOSEGAMELADY_ARROW_OFFSET_Y (-7)

	#define GIRL_NAME_X				(m_dispX >> 1)
	#define GIRL_NAME_Y				((m_dispX < m_dispY) ? 52 : 29)
	#define GIRL_LOCKED_Y			((m_dispX < m_dispY) ? (GIRL_NAME_Y + 30) : (GIRL_NAME_Y + 20))

	#define GIRL_DESCRIPTION_X		(m_dispX >> 1)
	#define GIRL_DESCRIPTION_Y		(GIRL_NAME_Y + 24)

	#define CHOOSEGAMELADY_GIRL_Y (IS_PORTRAIT ? 150 : 98)
	#define CHOOSEGAMELADY_GIRL1_X 0
	#define CHOOSEGAMELADY_GIRL2_X (IS_PORTRAIT ? 85 : 120)
	#define CHOOSEGAMELADY_GIRL3_X (IS_PORTRAIT ? 165 : 245)

	#define CHOOSEGAMELADY_SELECTED_GIRL_Y_OFFSET (IS_PORTRAIT ? -34 : -18)

	#define DUEL_BET_BOX_STEP				16
	#define DUEL_BET_BOX_TITLE_H			20
	#define DUEL_BET_BOX_MARGIN_Y			6
	#define DUEL_BET_BOX_W					200
	#define DUEL_BET_BOX_H					(DUEL_BET_BOX_STEP * 3 + DUEL_BET_BOX_TITLE_H + 2 * DUEL_BET_BOX_MARGIN_Y)
	#define DUEL_BET_BOX_X					((m_dispX - DUEL_BET_BOX_W) >> 1)
	#define DUEL_BET_BOX_Y					((m_dispY - DUEL_BET_BOX_H) >> 1)

	#define GLOBALBOTTOMBAR_INFO_Y (IS_PORTRAIT ? m_dispY - 30 : m_dispY - 13)
	#define GLOBALBOTTOMBAR_MONEY_X (IS_PORTRAIT ? 2 : 25)
	#define GLOBALBOTTOMBAR_COMPLETION_X (IS_PORTRAIT ? m_dispX - 2 : m_dispX - 25)

	#define CURRENTCARINFO_BOX_Y 21
	#define CURRENTCARINFO_BOX_HEIGHT (IS_PORTRAIT ? 85 : 65)
	#define CURRENTCARINFO_BOX_HEIGHT2 13
	
	#define CHOOSE_RIDE_NAME_Y						(IS_PORTRAIT ? 132 : 102)
	#define CHOOSE_RIDE_NAME_H						(CHOOSE_RIDE_NAME_Y - 9)

	#define CURRENTCARINFO_X						((m_dispX >> 1) - 5)
	#define CURRENTCARINFO_TXT_X					((m_dispX >> 1) + 5)
	#define CURRENTCARINFO_Y						42 // (IS_PORTRAIT ? 26 : 17)
	#define CURRENTCARINFO_SPACING					(IS_PORTRAIT ? 15 : 13)
	#define CURRENTCARINFO_LEFT_ALIGNED_TEXT_X		170
	#define CURRENTCARINFO_RIGHT_ALIGNED_TEXT_X		105

	#define CURRENTCARINFO_LOGO_X					30 // 54
	#define CURRENTCARINFO_LOGO_Y					(IS_PORTRAIT ? 70 : 60)

	#define CURRENTRECORDS_X						((m_dispX >> 1) -5)
	#define CURRENTRECORDS_TXT_X					(CURRENTRECORDS_X + 10)

	#define TUNING_NAME_Y			(IS_PORTRAIT ? 102 : 102)
	#define TUNING_NAME_H			(TUNING_NAME_Y - 9)

	#define CURRENTCARTUNINGINFO_BOX_YS 21
	#define CURRENTCARTUNINGINFO_BOX_H 78

	#define CURRENTCARTUNINGINFO_ICONS_Y 120//180 //SEFU 120

	#define CURRENTCARTUNINGINFO_ARROWS_Y_OFFSET (-18)

	#define CURRENTCARTUNINGINFOLIST_Y			40//100 //SEFU 40
	#define CURRENTCARTUNINGINFOLIST_SPACING	15

	#define CURRENTCARTUNINGINFOLIST_LOGO_X 185//35 //SEFU 185
	#define CURRENTCARTUNINGINFOLIST_LOGO_Y 67

	#define TUNING_BOX_PARTS_PER_COLUMN		4
	#define TUNING_BOX_W_MAX				130
	#define TUNING_BOX_H					70
	#define TUNING_BOX_COLORS_H				70
	#define TUNING_BOX_X_RIGHT				(IS_PORTRAIT ? 240 : 290)
	#define TUNING_BOX_Y					26
	#define	TUNING_BOX_COLOR_FILL			0x0000
	#define TUNING_BOX_BORDER				0x0F0F
	#define TUNING_BOX_LEFT_MARGIN			4
	#define TUNING_BOX_ARROW_X				12
	#define TUNING_BOX_TOP_MARGIN			9
	#define TUNING_BOX_COLOR_Y_MARGIN		9

	#define TUNING_BOX_ARROW_WIDTH			10

	#define TUNING_BOX_NEW_OFFSET_X			110

	#define CURRENTCARTUNINGINFOLIST_ICONS_TEXT_X		4
	#define CURRENTCARTUNINGINFOLIST_ICONS_TEXT_Y		142 //200 //SEFU 142

	#define CHOOSEYOURRIDE_SCROLLBAR_STEP_X 12
	#define CHOOSEYOURRIDE_SCROLLBAR_START_X (m_dispX/2) - ((stepX*12) >> 1)

	#define MAINSTATE_MENU_X			40
	#define MAINSTATE_MENU_Y			60	
	#define MAINSTATE_MENU_SPACING		20	
	
#else
	#error please define one of them
#endif

#ifdef R176x208
	#define FRAME_BOTTOM_Y					(lib2d.m_dispY - 10)
#else
	#define FRAME_BOTTOM_Y					(lib2d.m_dispY - 12)
#endif
#if defined USE_CHINESE_UNICODE_FONT
	#define FRAME_BOTTOM_CHINESE_Y					(lib2d.m_dispY - 20)
#endif

#define TUNING_SCREEN_ICONS_COUNT		(IS_PORTRAIT ? 7 : 11)
#define ICON_NEW_OFFSET_X				14
/*
#define RECORDS_X						(m_dispX >> 1)
#define RECORDS_TXT_X					(RECORDS_X + 10)
*/
#endif	// ! DEMO_GARAGE_MENU_DEFINES__INCLUDED__

