												
///////////////////////////////////////// 		 
//                                     //		 
//           MAKE SOUNDS               //		 
//                                     //		 
//    Do not change, current file      //		 
//  Was generated by 'MakeSounds.bat'  //		 
//                                     //		 
/////////////////////////////////////////		
#include "SoundsTable.h"								
												
const char * const SOUND_FILE[]=								
{												
SOUND_BONUS_PICK_UP_ITEM_FILE,		  								
SOUND_BONUS_PICK_UP_NITRO_FILE,		  								
SOUND_CAR_BIG_CRASH_FILE,		  								
SOUND_CAR_BRAKE_FILE,		  								
SOUND_CAR_CLUTCH_FILE,		  								
SOUND_CAR_DRIFT_FILE,		  								
SOUND_CAR_ENGINE_4K_FILE,		  								
SOUND_CAR_ENGINE_8K_FILE,		  								
SOUND_CAR_ENGINE_MOTORBIKE_FILE,		  								
SOUND_CAR_ENGINE_MUSCLE_FILE,		  								
SOUND_CAR_ENGINE_ROAR_FILE,		  								
SOUND_CAR_ENGINE_START_FILE,		  								
SOUND_CAR_HELICOPTER_LOOP_FILE,		  								
SOUND_CAR_IMPACT_WALL_FILE,		  								
SOUND_CAR_NITRO_BOOST_FILE,		  								
SOUND_CAR_OBJECT_IMPACT_WOODBLOCK_FILE,		  								
SOUND_CAR_POLICE_SIREN_SLOW_FILE,		  								
SOUND_CAR_SFX_CAR_JUMP_FILE,		  								
SOUND_CAR_SFX_CAR_PASS_BY_FILE,		  								
SOUND_CAR_SUPERDRIFT_FILE,		  								
SOUND_MENU_BACK_FILE,		  								
SOUND_MENU_CONFIRM_FILE,		  								
SOUND_MENU_MOVE_FILE,		  								
SOUND_COUNTER_1_FILE,		  								
SOUND_COUNTER_1ST_FILE,		  								
SOUND_COUNTER_2_FILE,		  								
SOUND_COUNTER_2ND_FILE,		  								
SOUND_COUNTER_3_FILE,		  								
SOUND_COUNTER_3RD_FILE,		  								
SOUND_COUNTER_GO_FILE,		  								
SOUND_COUNTER_LAST_PLACE_FILE,		  								
SOUND_COUNTER_YOU_WIN_FILE,		  								
SOUND_GRIND_SFX_GRIND_LOOP_FILE,		  								
SOUND_VFX_VFX_GIRL1_FILE,		  								
SOUND_VFX_VFX_GIRL2_FILE,		  								
SOUND_VFX_VFX_GIRL3_FILE,		  								
};												
		  										
												
const char * const MUSIC_FILE[]=								
{												
MUSIC_MUSIC_M_BGM1_FILE,											
MUSIC_MUSIC_M_BGM2_FILE,											
MUSIC_MUSIC_M_BGM3_FILE,											
MUSIC_MUSIC_M_BGM4_FILE,											
MUSIC_MUSIC_M_BGM5_FILE,											
MUSIC_MUSIC_M_BGM6_FILE,											
MUSIC_MUSIC_M_LOSE_FILE,											
MUSIC_MUSIC_M_MENU_FILE,											
MUSIC_MUSIC_M_TITLE_FILE,											
MUSIC_MUSIC_M_WIN_FILE,											
};												
		  										
